// Generated by rstantools.  Do not edit by hand.

/*
    moultmcmcExtra is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    moultmcmcExtra is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with moultmcmcExtra.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_uz2_linpred_annual_ranef_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 158> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 34, column 2 to column 28)",
  " (in 'string', line 35, column 2 to column 30)",
  " (in 'string', line 36, column 2 to column 34)",
  " (in 'string', line 37, column 2 to column 30)",
  " (in 'string', line 38, column 2 to column 34)",
  " (in 'string', line 39, column 2 to column 29)",
  " (in 'string', line 40, column 2 to column 33)",
  " (in 'string', line 43, column 2 to column 44)",
  " (in 'string', line 45, column 2 to column 62)",
  " (in 'string', line 46, column 2 to column 67)",
  " (in 'string', line 47, column 2 to column 87)",
  " (in 'string', line 48, column 2 to column 95)",
  " (in 'string', line 105, column 2 to column 32)",
  " (in 'string', line 106, column 2 to column 34)",
  " (in 'string', line 107, column 2 to column 51)",
  " (in 'string', line 111, column 4 to column 31)",
  " (in 'string', line 110, column 9 to line 112, column 3)",
  " (in 'string', line 109, column 4 to column 62)",
  " (in 'string', line 108, column 21 to line 110, column 3)",
  " (in 'string', line 108, column 2 to line 112, column 3)",
  " (in 'string', line 116, column 4 to column 31)",
  " (in 'string', line 115, column 9 to line 117, column 3)",
  " (in 'string', line 114, column 4 to column 64)",
  " (in 'string', line 113, column 22 to line 115, column 3)",
  " (in 'string', line 113, column 2 to line 117, column 3)",
  " (in 'string', line 119, column 11 to column 16)",
  " (in 'string', line 119, column 4 to column 20)",
  " (in 'string', line 120, column 11 to column 18)",
  " (in 'string', line 120, column 4 to column 22)",
  " (in 'string', line 121, column 11 to column 16)",
  " (in 'string', line 121, column 4 to column 20)",
  " (in 'string', line 122, column 11 to column 30)",
  " (in 'string', line 122, column 4 to column 35)",
  " (in 'string', line 123, column 11 to column 30)",
  " (in 'string', line 123, column 4 to column 36)",
  " (in 'string', line 124, column 11 to column 30)",
  " (in 'string', line 124, column 4 to column 38)",
  " (in 'string', line 125, column 4 to column 68)",
  " (in 'string', line 126, column 4 to column 72)",
  " (in 'string', line 127, column 4 to column 38)",
  " (in 'string', line 133, column 26 to line 134, column 88)",
  " (in 'string', line 133, column 6 to line 134, column 88)",
  " (in 'string', line 135, column 26 to line 138, column 73)",
  " (in 'string', line 135, column 6 to line 138, column 73)",
  " (in 'string', line 132, column 11 to line 139, column 5)",
  " (in 'string', line 129, column 26 to column 76)",
  " (in 'string', line 129, column 6 to column 76)",
  " (in 'string', line 130, column 26 to line 131, column 67)",
  " (in 'string', line 130, column 6 to line 131, column 67)",
  " (in 'string', line 128, column 21 to line 132, column 5)",
  " (in 'string', line 128, column 4 to line 139, column 5)",
  " (in 'string', line 141, column 6 to line 143, column 59)",
  " (in 'string', line 140, column 4 to line 143, column 59)",
  " (in 'string', line 144, column 4 to column 56)",
  " (in 'string', line 118, column 17 to line 145, column 3)",
  " (in 'string', line 118, column 2 to line 145, column 3)",
  " (in 'string', line 51, column 9 to column 14)",
  " (in 'string', line 51, column 2 to column 18)",
  " (in 'string', line 52, column 9 to column 16)",
  " (in 'string', line 52, column 2 to column 20)",
  " (in 'string', line 53, column 9 to column 14)",
  " (in 'string', line 53, column 2 to column 18)",
  " (in 'string', line 54, column 9 to column 28)",
  " (in 'string', line 54, column 2 to column 33)",
  " (in 'string', line 55, column 9 to column 28)",
  " (in 'string', line 55, column 2 to column 34)",
  " (in 'string', line 56, column 9 to column 28)",
  " (in 'string', line 56, column 2 to column 36)",
  " (in 'string', line 57, column 2 to column 66)",
  " (in 'string', line 58, column 2 to column 70)",
  " (in 'string', line 59, column 2 to column 36)",
  " (in 'string', line 65, column 24 to line 66, column 86)",
  " (in 'string', line 65, column 4 to line 66, column 86)",
  " (in 'string', line 67, column 24 to line 70, column 71)",
  " (in 'string', line 67, column 4 to line 70, column 71)",
  " (in 'string', line 64, column 9 to line 71, column 3)",
  " (in 'string', line 61, column 24 to column 74)",
  " (in 'string', line 61, column 4 to column 74)",
  " (in 'string', line 62, column 24 to line 63, column 65)",
  " (in 'string', line 62, column 4 to line 63, column 65)",
  " (in 'string', line 60, column 19 to line 64, column 3)",
  " (in 'string', line 60, column 2 to line 71, column 3)",
  " (in 'string', line 73, column 4 to line 75, column 57)",
  " (in 'string', line 72, column 2 to line 75, column 57)",
  " (in 'string', line 76, column 2 to column 47)",
  " (in 'string', line 78, column 2 to column 44)",
  " (in 'string', line 79, column 2 to column 48)",
  " (in 'string', line 85, column 4 to column 47)",
  " (in 'string', line 85, column 42 to column 45)",
  " (in 'string', line 85, column 37 to column 40)",
  " (in 'string', line 86, column 4 to column 44)",
  " (in 'string', line 86, column 39 to column 42)",
  " (in 'string', line 86, column 36 to column 37)",
  " (in 'string', line 84, column 9 to line 87, column 3)",
  " (in 'string', line 82, column 4 to column 37)",
  " (in 'string', line 83, column 4 to column 34)",
  " (in 'string', line 81, column 23 to line 84, column 3)",
  " (in 'string', line 81, column 2 to line 87, column 3)",
  " (in 'string', line 90, column 32 to column 67)",
  " (in 'string', line 90, column 6 to column 67)",
  " (in 'string', line 89, column 23 to line 91, column 5)",
  " (in 'string', line 89, column 4 to line 91, column 5)",
  " (in 'string', line 93, column 32 to column 67)",
  " (in 'string', line 93, column 6 to column 67)",
  " (in 'string', line 92, column 24 to line 94, column 5)",
  " (in 'string', line 92, column 4 to line 94, column 5)",
  " (in 'string', line 96, column 32 to column 67)",
  " (in 'string', line 96, column 6 to column 67)",
  " (in 'string', line 95, column 26 to line 97, column 5)",
  " (in 'string', line 95, column 4 to line 97, column 5)",
  " (in 'string', line 88, column 19 to line 98, column 3)",
  " (in 'string', line 88, column 2 to line 98, column 3)",
  " (in 'string', line 99, column 2 to column 34)",
  " (in 'string', line 100, column 2 to column 34)",
  " (in 'string', line 101, column 2 to column 34)",
  " (in 'string', line 7, column 2 to column 34)",
  " (in 'string', line 8, column 2 to column 15)",
  " (in 'string', line 9, column 2 to column 30)",
  " (in 'string', line 10, column 2 to column 28)",
  " (in 'string', line 12, column 2 to column 21)",
  " (in 'string', line 13, column 2 to column 23)",
  " (in 'string', line 14, column 2 to column 21)",
  " (in 'string', line 16, column 9 to column 14)",
  " (in 'string', line 16, column 2 to column 26)",
  " (in 'string', line 17, column 9 to column 16)",
  " (in 'string', line 17, column 2 to column 30)",
  " (in 'string', line 18, column 26 to column 33)",
  " (in 'string', line 18, column 2 to column 49)",
  " (in 'string', line 19, column 9 to column 14)",
  " (in 'string', line 19, column 2 to column 26)",
  " (in 'string', line 21, column 2 to column 14)",
  " (in 'string', line 22, column 42 to column 61)",
  " (in 'string', line 22, column 2 to column 63)",
  " (in 'string', line 23, column 2 to column 32)",
  " (in 'string', line 24, column 2 to column 33)",
  " (in 'string', line 26, column 2 to column 16)",
  " (in 'string', line 27, column 9 to column 28)",
  " (in 'string', line 27, column 30 to column 39)",
  " (in 'string', line 27, column 2 to column 46)",
  " (in 'string', line 28, column 2 to column 17)",
  " (in 'string', line 29, column 9 to column 28)",
  " (in 'string', line 29, column 30 to column 40)",
  " (in 'string', line 29, column 2 to column 48)",
  " (in 'string', line 30, column 2 to column 19)",
  " (in 'string', line 31, column 9 to column 28)",
  " (in 'string', line 31, column 30 to column 42)",
  " (in 'string', line 31, column 2 to column 52)",
  " (in 'string', line 34, column 9 to column 18)",
  " (in 'string', line 35, column 9 to column 19)",
  " (in 'string', line 36, column 9 to column 21)",
  " (in 'string', line 37, column 9 to column 16)",
  " (in 'string', line 38, column 9 to column 16)",
  " (in 'string', line 47, column 9 to column 16)",
  " (in 'string', line 48, column 9 to column 16)",
  " (in 'string', line 105, column 9 to column 18)",
  " (in 'string', line 106, column 9 to column 19)",
  " (in 'string', line 107, column 9 to column 41)"};
#include <stan_meta_header.hpp>
class model_uz2_linpred_annual_ranef final : public model_base_crtp<model_uz2_linpred_annual_ranef> {
private:
  int flat_prior;
  double beta_sd;
  int lumped;
  int llik;
  int N_old;
  int N_moult;
  int N_new;
  Eigen::Matrix<double,-1,1> old_dates_data__;
  Eigen::Matrix<double,-1,1> moult_dates_data__;
  Eigen::Matrix<double,-1,1> moult_indices_data__;
  Eigen::Matrix<double,-1,1> new_dates_data__;
  int N_years;
  std::vector<int> year_factor;
  int ranef_mu;
  int ranef_tau;
  int N_pred_mu;
  Eigen::Matrix<double,-1,-1> X_mu_data__;
  int N_pred_tau;
  Eigen::Matrix<double,-1,-1> X_tau_data__;
  int N_pred_sigma;
  Eigen::Matrix<double,-1,-1> X_sigma_data__;
  int log_lik_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> old_dates{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> moult_dates{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> moult_indices{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> new_dates{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_mu{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_tau{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_sigma{nullptr, 0, 0};
public:
  ~model_uz2_linpred_annual_ranef() {}
  model_uz2_linpred_annual_ranef(stan::io::var_context& context__,
                                 unsigned int random_seed__ = 0,
                                 std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_uz2_linpred_annual_ranef_namespace::model_uz2_linpred_annual_ranef";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 116;
      context__.validate_dims("data initialization", "flat_prior", "int",
        std::vector<size_t>{});
      flat_prior = std::numeric_limits<int>::min();
      current_statement__ = 116;
      flat_prior = context__.vals_i("flat_prior")[(1 - 1)];
      current_statement__ = 116;
      stan::math::check_greater_or_equal(function__, "flat_prior",
        flat_prior, 0);
      current_statement__ = 116;
      stan::math::check_less_or_equal(function__, "flat_prior", flat_prior, 1);
      current_statement__ = 117;
      context__.validate_dims("data initialization", "beta_sd", "double",
        std::vector<size_t>{});
      beta_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 117;
      beta_sd = context__.vals_r("beta_sd")[(1 - 1)];
      current_statement__ = 118;
      context__.validate_dims("data initialization", "lumped", "int",
        std::vector<size_t>{});
      lumped = std::numeric_limits<int>::min();
      current_statement__ = 118;
      lumped = context__.vals_i("lumped")[(1 - 1)];
      current_statement__ = 118;
      stan::math::check_greater_or_equal(function__, "lumped", lumped, 0);
      current_statement__ = 118;
      stan::math::check_less_or_equal(function__, "lumped", lumped, 1);
      current_statement__ = 119;
      context__.validate_dims("data initialization", "llik", "int",
        std::vector<size_t>{});
      llik = std::numeric_limits<int>::min();
      current_statement__ = 119;
      llik = context__.vals_i("llik")[(1 - 1)];
      current_statement__ = 119;
      stan::math::check_greater_or_equal(function__, "llik", llik, 0);
      current_statement__ = 119;
      stan::math::check_less_or_equal(function__, "llik", llik, 1);
      current_statement__ = 120;
      context__.validate_dims("data initialization", "N_old", "int",
        std::vector<size_t>{});
      N_old = std::numeric_limits<int>::min();
      current_statement__ = 120;
      N_old = context__.vals_i("N_old")[(1 - 1)];
      current_statement__ = 120;
      stan::math::check_greater_or_equal(function__, "N_old", N_old, 0);
      current_statement__ = 121;
      context__.validate_dims("data initialization", "N_moult", "int",
        std::vector<size_t>{});
      N_moult = std::numeric_limits<int>::min();
      current_statement__ = 121;
      N_moult = context__.vals_i("N_moult")[(1 - 1)];
      current_statement__ = 121;
      stan::math::check_greater_or_equal(function__, "N_moult", N_moult, 0);
      current_statement__ = 122;
      context__.validate_dims("data initialization", "N_new", "int",
        std::vector<size_t>{});
      N_new = std::numeric_limits<int>::min();
      current_statement__ = 122;
      N_new = context__.vals_i("N_new")[(1 - 1)];
      current_statement__ = 122;
      stan::math::check_greater_or_equal(function__, "N_new", N_new, 0);
      current_statement__ = 123;
      stan::math::validate_non_negative_index("old_dates", "N_old", N_old);
      current_statement__ = 124;
      context__.validate_dims("data initialization", "old_dates", "double",
        std::vector<size_t>{static_cast<size_t>(N_old)});
      old_dates_data__ = Eigen::Matrix<double,-1,1>::Constant(N_old,
                           std::numeric_limits<double>::quiet_NaN());
      new (&old_dates)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(old_dates_data__.data(),
        N_old);
      {
        std::vector<local_scalar_t__> old_dates_flat__;
        current_statement__ = 124;
        old_dates_flat__ = context__.vals_r("old_dates");
        current_statement__ = 124;
        pos__ = 1;
        current_statement__ = 124;
        for (int sym1__ = 1; sym1__ <= N_old; ++sym1__) {
          current_statement__ = 124;
          stan::model::assign(old_dates, old_dates_flat__[(pos__ - 1)],
            "assigning variable old_dates", stan::model::index_uni(sym1__));
          current_statement__ = 124;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 125;
      stan::math::validate_non_negative_index("moult_dates", "N_moult",
        N_moult);
      current_statement__ = 126;
      context__.validate_dims("data initialization", "moult_dates", "double",
        std::vector<size_t>{static_cast<size_t>(N_moult)});
      moult_dates_data__ = Eigen::Matrix<double,-1,1>::Constant(N_moult,
                             std::numeric_limits<double>::quiet_NaN());
      new (&moult_dates)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(moult_dates_data__.data(),
        N_moult);
      {
        std::vector<local_scalar_t__> moult_dates_flat__;
        current_statement__ = 126;
        moult_dates_flat__ = context__.vals_r("moult_dates");
        current_statement__ = 126;
        pos__ = 1;
        current_statement__ = 126;
        for (int sym1__ = 1; sym1__ <= N_moult; ++sym1__) {
          current_statement__ = 126;
          stan::model::assign(moult_dates, moult_dates_flat__[(pos__ - 1)],
            "assigning variable moult_dates", stan::model::index_uni(sym1__));
          current_statement__ = 126;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 127;
      stan::math::validate_non_negative_index("moult_indices", "N_moult",
        N_moult);
      current_statement__ = 128;
      context__.validate_dims("data initialization", "moult_indices",
        "double", std::vector<size_t>{static_cast<size_t>(N_moult)});
      moult_indices_data__ = Eigen::Matrix<double,-1,1>::Constant(N_moult,
                               std::numeric_limits<double>::quiet_NaN());
      new (&moult_indices)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(moult_indices_data__.data(),
        N_moult);
      {
        std::vector<local_scalar_t__> moult_indices_flat__;
        current_statement__ = 128;
        moult_indices_flat__ = context__.vals_r("moult_indices");
        current_statement__ = 128;
        pos__ = 1;
        current_statement__ = 128;
        for (int sym1__ = 1; sym1__ <= N_moult; ++sym1__) {
          current_statement__ = 128;
          stan::model::assign(moult_indices, moult_indices_flat__[(pos__ -
            1)], "assigning variable moult_indices",
            stan::model::index_uni(sym1__));
          current_statement__ = 128;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 128;
      stan::math::check_greater_or_equal(function__, "moult_indices",
        moult_indices, 0);
      current_statement__ = 128;
      stan::math::check_less_or_equal(function__, "moult_indices",
        moult_indices, 1);
      current_statement__ = 129;
      stan::math::validate_non_negative_index("new_dates", "N_new", N_new);
      current_statement__ = 130;
      context__.validate_dims("data initialization", "new_dates", "double",
        std::vector<size_t>{static_cast<size_t>(N_new)});
      new_dates_data__ = Eigen::Matrix<double,-1,1>::Constant(N_new,
                           std::numeric_limits<double>::quiet_NaN());
      new (&new_dates)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(new_dates_data__.data(),
        N_new);
      {
        std::vector<local_scalar_t__> new_dates_flat__;
        current_statement__ = 130;
        new_dates_flat__ = context__.vals_r("new_dates");
        current_statement__ = 130;
        pos__ = 1;
        current_statement__ = 130;
        for (int sym1__ = 1; sym1__ <= N_new; ++sym1__) {
          current_statement__ = 130;
          stan::model::assign(new_dates, new_dates_flat__[(pos__ - 1)],
            "assigning variable new_dates", stan::model::index_uni(sym1__));
          current_statement__ = 130;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 131;
      context__.validate_dims("data initialization", "N_years", "int",
        std::vector<size_t>{});
      N_years = std::numeric_limits<int>::min();
      current_statement__ = 131;
      N_years = context__.vals_i("N_years")[(1 - 1)];
      current_statement__ = 132;
      stan::math::validate_non_negative_index("year_factor",
        "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
      current_statement__ = 133;
      context__.validate_dims("data initialization", "year_factor", "int",
        std::vector<size_t>{static_cast<size_t>(((N_old + N_moult) + N_new))});
      year_factor = std::vector<int>(((N_old + N_moult) + N_new),
                      std::numeric_limits<int>::min());
      current_statement__ = 133;
      year_factor = context__.vals_i("year_factor");
      current_statement__ = 133;
      stan::math::check_greater_or_equal(function__, "year_factor",
        year_factor, 1);
      current_statement__ = 133;
      stan::math::check_less_or_equal(function__, "year_factor", year_factor,
        N_years);
      current_statement__ = 134;
      context__.validate_dims("data initialization", "ranef_mu", "int",
        std::vector<size_t>{});
      ranef_mu = std::numeric_limits<int>::min();
      current_statement__ = 134;
      ranef_mu = context__.vals_i("ranef_mu")[(1 - 1)];
      current_statement__ = 134;
      stan::math::check_greater_or_equal(function__, "ranef_mu", ranef_mu, 0);
      current_statement__ = 134;
      stan::math::check_less_or_equal(function__, "ranef_mu", ranef_mu, 1);
      current_statement__ = 135;
      context__.validate_dims("data initialization", "ranef_tau", "int",
        std::vector<size_t>{});
      ranef_tau = std::numeric_limits<int>::min();
      current_statement__ = 135;
      ranef_tau = context__.vals_i("ranef_tau")[(1 - 1)];
      current_statement__ = 135;
      stan::math::check_greater_or_equal(function__, "ranef_tau", ranef_tau,
        0);
      current_statement__ = 135;
      stan::math::check_less_or_equal(function__, "ranef_tau", ranef_tau, 1);
      current_statement__ = 136;
      context__.validate_dims("data initialization", "N_pred_mu", "int",
        std::vector<size_t>{});
      N_pred_mu = std::numeric_limits<int>::min();
      current_statement__ = 136;
      N_pred_mu = context__.vals_i("N_pred_mu")[(1 - 1)];
      current_statement__ = 137;
      stan::math::validate_non_negative_index("X_mu",
        "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
      current_statement__ = 138;
      stan::math::validate_non_negative_index("X_mu", "N_pred_mu", N_pred_mu);
      current_statement__ = 139;
      context__.validate_dims("data initialization", "X_mu", "double",
        std::vector<size_t>{static_cast<size_t>(((N_old + N_moult) + N_new)),
          static_cast<size_t>(N_pred_mu)});
      X_mu_data__ = Eigen::Matrix<double,-1,-1>::Constant(((N_old + N_moult)
                      + N_new), N_pred_mu,
                      std::numeric_limits<double>::quiet_NaN());
      new (&X_mu) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_mu_data__.data(),
        ((N_old + N_moult) + N_new), N_pred_mu);
      {
        std::vector<local_scalar_t__> X_mu_flat__;
        current_statement__ = 139;
        X_mu_flat__ = context__.vals_r("X_mu");
        current_statement__ = 139;
        pos__ = 1;
        current_statement__ = 139;
        for (int sym1__ = 1; sym1__ <= N_pred_mu; ++sym1__) {
          current_statement__ = 139;
          for (int sym2__ = 1; sym2__ <= ((N_old + N_moult) +
               N_new); ++sym2__) {
            current_statement__ = 139;
            stan::model::assign(X_mu, X_mu_flat__[(pos__ - 1)],
              "assigning variable X_mu", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 139;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 140;
      context__.validate_dims("data initialization", "N_pred_tau", "int",
        std::vector<size_t>{});
      N_pred_tau = std::numeric_limits<int>::min();
      current_statement__ = 140;
      N_pred_tau = context__.vals_i("N_pred_tau")[(1 - 1)];
      current_statement__ = 141;
      stan::math::validate_non_negative_index("X_tau",
        "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
      current_statement__ = 142;
      stan::math::validate_non_negative_index("X_tau", "N_pred_tau",
        N_pred_tau);
      current_statement__ = 143;
      context__.validate_dims("data initialization", "X_tau", "double",
        std::vector<size_t>{static_cast<size_t>(((N_old + N_moult) + N_new)),
          static_cast<size_t>(N_pred_tau)});
      X_tau_data__ = Eigen::Matrix<double,-1,-1>::Constant(((N_old + N_moult)
                       + N_new), N_pred_tau,
                       std::numeric_limits<double>::quiet_NaN());
      new (&X_tau)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_tau_data__.data(), ((N_old
        + N_moult) + N_new), N_pred_tau);
      {
        std::vector<local_scalar_t__> X_tau_flat__;
        current_statement__ = 143;
        X_tau_flat__ = context__.vals_r("X_tau");
        current_statement__ = 143;
        pos__ = 1;
        current_statement__ = 143;
        for (int sym1__ = 1; sym1__ <= N_pred_tau; ++sym1__) {
          current_statement__ = 143;
          for (int sym2__ = 1; sym2__ <= ((N_old + N_moult) +
               N_new); ++sym2__) {
            current_statement__ = 143;
            stan::model::assign(X_tau, X_tau_flat__[(pos__ - 1)],
              "assigning variable X_tau", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 143;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 144;
      context__.validate_dims("data initialization", "N_pred_sigma", "int",
        std::vector<size_t>{});
      N_pred_sigma = std::numeric_limits<int>::min();
      current_statement__ = 144;
      N_pred_sigma = context__.vals_i("N_pred_sigma")[(1 - 1)];
      current_statement__ = 145;
      stan::math::validate_non_negative_index("X_sigma",
        "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
      current_statement__ = 146;
      stan::math::validate_non_negative_index("X_sigma", "N_pred_sigma",
        N_pred_sigma);
      current_statement__ = 147;
      context__.validate_dims("data initialization", "X_sigma", "double",
        std::vector<size_t>{static_cast<size_t>(((N_old + N_moult) + N_new)),
          static_cast<size_t>(N_pred_sigma)});
      X_sigma_data__ = Eigen::Matrix<double,-1,-1>::Constant(((N_old +
                         N_moult) + N_new), N_pred_sigma,
                         std::numeric_limits<double>::quiet_NaN());
      new (&X_sigma)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_sigma_data__.data(),
        ((N_old + N_moult) + N_new), N_pred_sigma);
      {
        std::vector<local_scalar_t__> X_sigma_flat__;
        current_statement__ = 147;
        X_sigma_flat__ = context__.vals_r("X_sigma");
        current_statement__ = 147;
        pos__ = 1;
        current_statement__ = 147;
        for (int sym1__ = 1; sym1__ <= N_pred_sigma; ++sym1__) {
          current_statement__ = 147;
          for (int sym2__ = 1; sym2__ <= ((N_old + N_moult) +
               N_new); ++sym2__) {
            current_statement__ = 147;
            stan::model::assign(X_sigma, X_sigma_flat__[(pos__ - 1)],
              "assigning variable X_sigma", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 147;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 148;
      stan::math::validate_non_negative_index("beta_mu", "N_pred_mu",
        N_pred_mu);
      current_statement__ = 149;
      stan::math::validate_non_negative_index("beta_tau", "N_pred_tau",
        N_pred_tau);
      current_statement__ = 150;
      stan::math::validate_non_negative_index("beta_sigma", "N_pred_sigma",
        N_pred_sigma);
      current_statement__ = 151;
      stan::math::validate_non_negative_index("u_year_mean", "N_years",
        N_years);
      current_statement__ = 152;
      stan::math::validate_non_negative_index("u_year_duration", "N_years",
        N_years);
      current_statement__ = 153;
      stan::math::validate_non_negative_index("u_year_mean_star", "N_years",
        N_years);
      current_statement__ = 154;
      stan::math::validate_non_negative_index("u_year_duration_star",
        "N_years", N_years);
      current_statement__ = 155;
      stan::math::validate_non_negative_index("beta_mu_out", "N_pred_mu",
        N_pred_mu);
      current_statement__ = 156;
      stan::math::validate_non_negative_index("beta_tau_out", "N_pred_tau",
        N_pred_tau);
      current_statement__ = 157;
      log_lik_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 157;
      log_lik_1dim__ = (((N_old + N_moult) + N_new) * llik);
      current_statement__ = 157;
      stan::math::validate_non_negative_index("log_lik",
        "(N_old + N_moult + N_new) * llik", log_lik_1dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = N_pred_mu + N_pred_tau + N_pred_sigma + N_years +
      N_years + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_uz2_linpred_annual_ranef";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_uz2_linpred_annual_ranef_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta_mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_pred_mu,
          DUMMY_VAR__);
      current_statement__ = 1;
      beta_mu = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(N_pred_mu);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_tau =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_pred_tau,
          DUMMY_VAR__);
      current_statement__ = 2;
      beta_tau = in__.template read<
                   Eigen::Matrix<local_scalar_t__,-1,1>>(N_pred_tau);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_pred_sigma,
          DUMMY_VAR__);
      current_statement__ = 3;
      beta_sigma = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,1>>(N_pred_sigma);
      Eigen::Matrix<local_scalar_t__,-1,1> u_year_mean =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_years, DUMMY_VAR__);
      current_statement__ = 4;
      u_year_mean = in__.template read<
                      Eigen::Matrix<local_scalar_t__,-1,1>>(N_years);
      Eigen::Matrix<local_scalar_t__,-1,1> u_year_duration =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_years, DUMMY_VAR__);
      current_statement__ = 5;
      u_year_duration = in__.template read<
                          Eigen::Matrix<local_scalar_t__,-1,1>>(N_years);
      local_scalar_t__ sd_year_mean = DUMMY_VAR__;
      current_statement__ = 6;
      sd_year_mean = in__.template read_constrain_lb<local_scalar_t__,
                       jacobian__>(0, lp__);
      local_scalar_t__ sd_year_duration = DUMMY_VAR__;
      current_statement__ = 7;
      sd_year_duration = in__.template read_constrain_lb<local_scalar_t__,
                           jacobian__>(0, lp__);
      local_scalar_t__ sigma_intercept = DUMMY_VAR__;
      current_statement__ = 8;
      sigma_intercept = stan::math::exp(
                          stan::model::rvalue(beta_sigma, "beta_sigma",
                            stan::model::index_uni(1)));
      local_scalar_t__ beta_star = DUMMY_VAR__;
      current_statement__ = 9;
      beta_star = (stan::model::rvalue(beta_mu, "beta_mu",
                     stan::model::index_uni(1))
        + (ranef_mu * stan::math::mean(u_year_mean)));
      local_scalar_t__ tau_star = DUMMY_VAR__;
      current_statement__ = 10;
      tau_star = (stan::model::rvalue(beta_tau, "beta_tau",
                    stan::model::index_uni(1))
        + (ranef_tau * stan::math::mean(u_year_duration)));
      Eigen::Matrix<local_scalar_t__,-1,1> u_year_mean_star =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_years, DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(u_year_mean_star,
        stan::math::multiply(ranef_mu,
          stan::math::subtract(u_year_mean, stan::math::mean(u_year_mean))),
        "assigning variable u_year_mean_star");
      Eigen::Matrix<local_scalar_t__,-1,1> u_year_duration_star =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_years, DUMMY_VAR__);
      current_statement__ = 12;
      stan::model::assign(u_year_duration_star,
        stan::math::multiply(ranef_tau,
          stan::math::subtract(u_year_duration,
            stan::math::mean(u_year_duration))),
        "assigning variable u_year_duration_star");
      {
        current_statement__ = 57;
        stan::math::validate_non_negative_index("P", "N_old", N_old);
        Eigen::Matrix<local_scalar_t__,-1,1> P =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_old, DUMMY_VAR__);
        current_statement__ = 59;
        stan::math::validate_non_negative_index("q", "N_moult", N_moult);
        Eigen::Matrix<local_scalar_t__,-1,1> q =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_moult,
            DUMMY_VAR__);
        current_statement__ = 61;
        stan::math::validate_non_negative_index("R", "N_new", N_new);
        Eigen::Matrix<local_scalar_t__,-1,1> R =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_new, DUMMY_VAR__);
        current_statement__ = 63;
        stan::math::validate_non_negative_index("mu",
          "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
        Eigen::Matrix<local_scalar_t__,-1,1> mu =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(((N_old + N_moult) +
            N_new), DUMMY_VAR__);
        current_statement__ = 65;
        stan::math::validate_non_negative_index("tau",
          "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
        Eigen::Matrix<local_scalar_t__,-1,1> tau =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(((N_old + N_moult) +
            N_new), DUMMY_VAR__);
        current_statement__ = 67;
        stan::math::validate_non_negative_index("sigma",
          "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
        Eigen::Matrix<local_scalar_t__,-1,1> sigma =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(((N_old + N_moult) +
            N_new), DUMMY_VAR__);
        current_statement__ = 69;
        stan::model::assign(mu,
          stan::math::add(stan::math::multiply(X_mu, beta_mu),
            stan::math::multiply(ranef_mu,
              stan::model::rvalue(u_year_mean, "u_year_mean",
                stan::model::index_multi(year_factor)))),
          "assigning variable mu");
        current_statement__ = 70;
        stan::model::assign(tau,
          stan::math::add(stan::math::multiply(X_tau, beta_tau),
            stan::math::multiply(ranef_tau,
              stan::model::rvalue(u_year_duration, "u_year_duration",
                stan::model::index_multi(year_factor)))),
          "assigning variable tau");
        current_statement__ = 71;
        stan::model::assign(sigma,
          stan::math::exp(stan::math::multiply(X_sigma, beta_sigma)),
          "assigning variable sigma");
        current_statement__ = 82;
        if (stan::math::logical_eq(lumped, 0)) {
          current_statement__ = 78;
          for (int i = 1; i <= N_old; ++i) {
            current_statement__ = 77;
            stan::model::assign(P, (1 -
              stan::math::Phi(
                ((stan::model::rvalue(old_dates, "old_dates",
                    stan::model::index_uni(i)) -
                stan::model::rvalue(mu, "mu", stan::model::index_uni(i))) /
                stan::model::rvalue(sigma, "sigma", stan::model::index_uni(i))))),
              "assigning variable P", stan::model::index_uni(i));
          }
          current_statement__ = 80;
          for (int i = 1; i <= N_new; ++i) {
            current_statement__ = 79;
            stan::model::assign(R,
              stan::math::Phi(
                (((stan::model::rvalue(new_dates, "new_dates",
                     stan::model::index_uni(i)) -
                stan::model::rvalue(tau, "tau",
                  stan::model::index_uni(((i + N_old) + N_moult)))) -
                stan::model::rvalue(mu, "mu",
                  stan::model::index_uni(((i + N_old) + N_moult)))) /
                stan::model::rvalue(sigma, "sigma",
                  stan::model::index_uni(((i + N_old) + N_moult))))),
              "assigning variable R", stan::model::index_uni(i));
          }
        } else {
          current_statement__ = 73;
          for (int i = 1; i <= N_old; ++i) {
            current_statement__ = 72;
            stan::model::assign(P, ((1 -
              stan::math::Phi(
                ((stan::model::rvalue(old_dates, "old_dates",
                    stan::model::index_uni(i)) -
                stan::model::rvalue(mu, "mu", stan::model::index_uni(i))) /
                stan::model::rvalue(sigma, "sigma", stan::model::index_uni(i)))))
              +
              stan::math::Phi(
                (((stan::model::rvalue(old_dates, "old_dates",
                     stan::model::index_uni(i)) -
                stan::model::rvalue(tau, "tau", stan::model::index_uni(i))) -
                stan::model::rvalue(mu, "mu", stan::model::index_uni(i))) /
                stan::model::rvalue(sigma, "sigma", stan::model::index_uni(i))))),
              "assigning variable P", stan::model::index_uni(i));
          }
          current_statement__ = 75;
          for (int i = 1; i <= N_new; ++i) {
            current_statement__ = 74;
            stan::model::assign(R,
              (stan::math::Phi(
                 (((stan::model::rvalue(new_dates, "new_dates",
                      stan::model::index_uni(i)) -
                 stan::model::rvalue(tau, "tau",
                   stan::model::index_uni(((i + N_old) + N_moult)))) -
                 stan::model::rvalue(mu, "mu",
                   stan::model::index_uni(((i + N_old) + N_moult)))) /
                 stan::model::rvalue(sigma, "sigma",
                   stan::model::index_uni(((i + N_old) + N_moult))))) + (1 -
              stan::math::Phi(
                ((stan::model::rvalue(new_dates, "new_dates",
                    stan::model::index_uni(i)) -
                stan::model::rvalue(mu, "mu",
                  stan::model::index_uni(((i + N_old) + N_moult)))) /
                stan::model::rvalue(sigma, "sigma",
                  stan::model::index_uni(((i + N_old) + N_moult))))))),
              "assigning variable R", stan::model::index_uni(i));
          }
        }
        current_statement__ = 84;
        for (int i = 1; i <= N_moult; ++i) {
          current_statement__ = 83;
          stan::model::assign(q,
            (stan::math::log(
               stan::model::rvalue(tau, "tau",
                 stan::model::index_uni((i + N_old)))) +
            stan::math::normal_lpdf<false>(
              (stan::model::rvalue(moult_dates, "moult_dates",
                 stan::model::index_uni(i)) -
              (stan::model::rvalue(moult_indices, "moult_indices",
                 stan::model::index_uni(i)) *
              stan::model::rvalue(tau, "tau",
                stan::model::index_uni((i + N_old))))),
              stan::model::rvalue(mu, "mu",
                stan::model::index_uni((i + N_old))),
              stan::model::rvalue(sigma, "sigma",
                stan::model::index_uni((i + N_old))))),
            "assigning variable q", stan::model::index_uni(i));
        }
        current_statement__ = 85;
        lp_accum__.add(((stan::math::sum(stan::math::log(P)) +
          stan::math::sum(q)) + stan::math::sum(stan::math::log(R))));
        current_statement__ = 86;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(u_year_mean, 0,
                         sd_year_mean));
        current_statement__ = 87;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(u_year_duration, 0,
                         sd_year_duration));
        current_statement__ = 98;
        if (stan::math::logical_eq(flat_prior, 1)) {
          current_statement__ = 95;
          lp_accum__.add(stan::math::uniform_lpdf<propto__>(
                           stan::model::rvalue(beta_mu, "beta_mu",
                             stan::model::index_uni(1)), -366, 366));
          current_statement__ = 96;
          lp_accum__.add(stan::math::uniform_lpdf<propto__>(
                           stan::model::rvalue(beta_tau, "beta_tau",
                             stan::model::index_uni(1)), 0, 366));
        } else {
          current_statement__ = 88;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(beta_mu, "beta_mu",
                             stan::model::index_uni(1)), 150, 50));
          current_statement__ = 90;
          if (stan::math::logical_lt(
                stan::model::rvalue(beta_mu, "beta_mu",
                  stan::model::index_uni(1)), -366)) {
            current_statement__ = 90;
            lp_accum__.add(stan::math::negative_infinity());
          } else {
            current_statement__ = 89;
            if (stan::math::logical_gt(
                  stan::model::rvalue(beta_mu, "beta_mu",
                    stan::model::index_uni(1)), 366)) {
              current_statement__ = 89;
              lp_accum__.add(stan::math::negative_infinity());
            } else {
              current_statement__ = 89;
              lp_accum__.add(-stan::math::log_diff_exp(
                                stan::math::normal_lcdf(366, 150, 50),
                                stan::math::normal_lcdf(-366, 150, 50)));
            }
          }
          current_statement__ = 91;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(beta_tau, "beta_tau",
                             stan::model::index_uni(1)), 100, 30));
          current_statement__ = 93;
          if (stan::math::logical_lt(
                stan::model::rvalue(beta_tau, "beta_tau",
                  stan::model::index_uni(1)), 0)) {
            current_statement__ = 93;
            lp_accum__.add(stan::math::negative_infinity());
          } else {
            current_statement__ = 92;
            if (stan::math::logical_gt(
                  stan::model::rvalue(beta_tau, "beta_tau",
                    stan::model::index_uni(1)), 366)) {
              current_statement__ = 92;
              lp_accum__.add(stan::math::negative_infinity());
            } else {
              current_statement__ = 92;
              lp_accum__.add(-stan::math::log_diff_exp(
                                stan::math::normal_lcdf(366, 100, 30),
                                stan::math::normal_lcdf(0, 100, 30)));
            }
          }
        }
        current_statement__ = 112;
        if (stan::math::logical_gt(beta_sd, 0)) {
          current_statement__ = 102;
          if (stan::math::logical_gt(N_pred_mu, 1)) {
            current_statement__ = 100;
            for (int i = 2; i <= N_pred_mu; ++i) {
              current_statement__ = 99;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(beta_mu, "beta_mu",
                                 stan::model::index_uni(i)), 0, beta_sd));
            }
          }
          current_statement__ = 106;
          if (stan::math::logical_gt(N_pred_tau, 1)) {
            current_statement__ = 104;
            for (int i = 2; i <= N_pred_tau; ++i) {
              current_statement__ = 103;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(beta_tau, "beta_tau",
                                 stan::model::index_uni(i)), 0, beta_sd));
            }
          }
          current_statement__ = 110;
          if (stan::math::logical_gt(N_pred_sigma, 1)) {
            current_statement__ = 108;
            for (int i = 2; i <= N_pred_sigma; ++i) {
              current_statement__ = 107;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(beta_sigma, "beta_sigma",
                                 stan::model::index_uni(i)), 0, beta_sd));
            }
          }
        }
        current_statement__ = 113;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::model::rvalue(beta_sigma, "beta_sigma",
                           stan::model::index_uni(1)), 0, 2));
        current_statement__ = 114;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sd_year_mean, 0, 2));
        current_statement__ = 115;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sd_year_duration, 0,
                         2));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_uz2_linpred_annual_ranef_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> beta_mu =
        Eigen::Matrix<double,-1,1>::Constant(N_pred_mu,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta_mu = in__.template read<
                  Eigen::Matrix<local_scalar_t__,-1,1>>(N_pred_mu);
      Eigen::Matrix<double,-1,1> beta_tau =
        Eigen::Matrix<double,-1,1>::Constant(N_pred_tau,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta_tau = in__.template read<
                   Eigen::Matrix<local_scalar_t__,-1,1>>(N_pred_tau);
      Eigen::Matrix<double,-1,1> beta_sigma =
        Eigen::Matrix<double,-1,1>::Constant(N_pred_sigma,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      beta_sigma = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,1>>(N_pred_sigma);
      Eigen::Matrix<double,-1,1> u_year_mean =
        Eigen::Matrix<double,-1,1>::Constant(N_years,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      u_year_mean = in__.template read<
                      Eigen::Matrix<local_scalar_t__,-1,1>>(N_years);
      Eigen::Matrix<double,-1,1> u_year_duration =
        Eigen::Matrix<double,-1,1>::Constant(N_years,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      u_year_duration = in__.template read<
                          Eigen::Matrix<local_scalar_t__,-1,1>>(N_years);
      double sd_year_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      sd_year_mean = in__.template read_constrain_lb<local_scalar_t__,
                       jacobian__>(0, lp__);
      double sd_year_duration = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      sd_year_duration = in__.template read_constrain_lb<local_scalar_t__,
                           jacobian__>(0, lp__);
      double sigma_intercept = std::numeric_limits<double>::quiet_NaN();
      double beta_star = std::numeric_limits<double>::quiet_NaN();
      double tau_star = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,1> u_year_mean_star =
        Eigen::Matrix<double,-1,1>::Constant(N_years,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> u_year_duration_star =
        Eigen::Matrix<double,-1,1>::Constant(N_years,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(beta_mu);
      out__.write(beta_tau);
      out__.write(beta_sigma);
      out__.write(u_year_mean);
      out__.write(u_year_duration);
      out__.write(sd_year_mean);
      out__.write(sd_year_duration);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 8;
      sigma_intercept = stan::math::exp(
                          stan::model::rvalue(beta_sigma, "beta_sigma",
                            stan::model::index_uni(1)));
      current_statement__ = 9;
      beta_star = (stan::model::rvalue(beta_mu, "beta_mu",
                     stan::model::index_uni(1))
        + (ranef_mu * stan::math::mean(u_year_mean)));
      current_statement__ = 10;
      tau_star = (stan::model::rvalue(beta_tau, "beta_tau",
                    stan::model::index_uni(1))
        + (ranef_tau * stan::math::mean(u_year_duration)));
      current_statement__ = 11;
      stan::model::assign(u_year_mean_star,
        stan::math::multiply(ranef_mu,
          stan::math::subtract(u_year_mean, stan::math::mean(u_year_mean))),
        "assigning variable u_year_mean_star");
      current_statement__ = 12;
      stan::model::assign(u_year_duration_star,
        stan::math::multiply(ranef_tau,
          stan::math::subtract(u_year_duration,
            stan::math::mean(u_year_duration))),
        "assigning variable u_year_duration_star");
      if (emit_transformed_parameters__) {
        out__.write(sigma_intercept);
        out__.write(beta_star);
        out__.write(tau_star);
        out__.write(u_year_mean_star);
        out__.write(u_year_duration_star);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> beta_mu_out =
        Eigen::Matrix<double,-1,1>::Constant(N_pred_mu,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> beta_tau_out =
        Eigen::Matrix<double,-1,1>::Constant(N_pred_tau,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(log_lik_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 20;
      if (stan::math::logical_gt(N_pred_mu, 1)) {
        current_statement__ = 18;
        stan::model::assign(beta_mu_out,
          stan::math::append_row(beta_star,
            stan::model::rvalue(beta_mu, "beta_mu",
              stan::model::index_min_max(2, N_pred_mu))),
          "assigning variable beta_mu_out");
      } else {
        current_statement__ = 16;
        stan::model::assign(beta_mu_out, beta_star,
          "assigning variable beta_mu_out", stan::model::index_uni(1));
      }
      current_statement__ = 25;
      if (stan::math::logical_gt(N_pred_tau, 1)) {
        current_statement__ = 23;
        stan::model::assign(beta_tau_out,
          stan::math::append_row(tau_star,
            stan::model::rvalue(beta_tau, "beta_tau",
              stan::model::index_min_max(2, N_pred_tau))),
          "assigning variable beta_tau_out");
      } else {
        current_statement__ = 21;
        stan::model::assign(beta_tau_out, tau_star,
          "assigning variable beta_tau_out", stan::model::index_uni(1));
      }
      current_statement__ = 56;
      if (stan::math::logical_eq(llik, 1)) {
        current_statement__ = 26;
        stan::math::validate_non_negative_index("P", "N_old", N_old);
        Eigen::Matrix<double,-1,1> P =
          Eigen::Matrix<double,-1,1>::Constant(N_old,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 28;
        stan::math::validate_non_negative_index("q", "N_moult", N_moult);
        Eigen::Matrix<double,-1,1> q =
          Eigen::Matrix<double,-1,1>::Constant(N_moult,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 30;
        stan::math::validate_non_negative_index("R", "N_new", N_new);
        Eigen::Matrix<double,-1,1> R =
          Eigen::Matrix<double,-1,1>::Constant(N_new,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 32;
        stan::math::validate_non_negative_index("mu",
          "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
        Eigen::Matrix<double,-1,1> mu =
          Eigen::Matrix<double,-1,1>::Constant(((N_old + N_moult) + N_new),
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 34;
        stan::math::validate_non_negative_index("tau",
          "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
        Eigen::Matrix<double,-1,1> tau =
          Eigen::Matrix<double,-1,1>::Constant(((N_old + N_moult) + N_new),
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 36;
        stan::math::validate_non_negative_index("sigma",
          "N_old + N_moult + N_new", ((N_old + N_moult) + N_new));
        Eigen::Matrix<double,-1,1> sigma =
          Eigen::Matrix<double,-1,1>::Constant(((N_old + N_moult) + N_new),
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 38;
        stan::model::assign(mu,
          stan::math::add(stan::math::multiply(X_mu, beta_mu),
            stan::math::multiply(ranef_mu,
              stan::model::rvalue(u_year_mean, "u_year_mean",
                stan::model::index_multi(year_factor)))),
          "assigning variable mu");
        current_statement__ = 39;
        stan::model::assign(tau,
          stan::math::add(stan::math::multiply(X_tau, beta_tau),
            stan::math::multiply(ranef_tau,
              stan::model::rvalue(u_year_duration, "u_year_duration",
                stan::model::index_multi(year_factor)))),
          "assigning variable tau");
        current_statement__ = 40;
        stan::model::assign(sigma,
          stan::math::exp(stan::math::multiply(X_sigma, beta_sigma)),
          "assigning variable sigma");
        current_statement__ = 51;
        if (stan::math::logical_eq(lumped, 0)) {
          current_statement__ = 47;
          for (int i = 1; i <= N_old; ++i) {
            current_statement__ = 46;
            stan::model::assign(P, (1 -
              stan::math::Phi(
                ((stan::model::rvalue(old_dates, "old_dates",
                    stan::model::index_uni(i)) -
                stan::model::rvalue(mu, "mu", stan::model::index_uni(i))) /
                stan::model::rvalue(sigma, "sigma", stan::model::index_uni(i))))),
              "assigning variable P", stan::model::index_uni(i));
          }
          current_statement__ = 49;
          for (int i = 1; i <= N_new; ++i) {
            current_statement__ = 48;
            stan::model::assign(R,
              stan::math::Phi(
                (((stan::model::rvalue(new_dates, "new_dates",
                     stan::model::index_uni(i)) -
                stan::model::rvalue(tau, "tau",
                  stan::model::index_uni(((i + N_old) + N_moult)))) -
                stan::model::rvalue(mu, "mu",
                  stan::model::index_uni(((i + N_old) + N_moult)))) /
                stan::model::rvalue(sigma, "sigma",
                  stan::model::index_uni(((i + N_old) + N_moult))))),
              "assigning variable R", stan::model::index_uni(i));
          }
        } else {
          current_statement__ = 42;
          for (int i = 1; i <= N_old; ++i) {
            current_statement__ = 41;
            stan::model::assign(P, ((1 -
              stan::math::Phi(
                ((stan::model::rvalue(old_dates, "old_dates",
                    stan::model::index_uni(i)) -
                stan::model::rvalue(mu, "mu", stan::model::index_uni(i))) /
                stan::model::rvalue(sigma, "sigma", stan::model::index_uni(i)))))
              +
              stan::math::Phi(
                (((stan::model::rvalue(old_dates, "old_dates",
                     stan::model::index_uni(i)) -
                stan::model::rvalue(tau, "tau", stan::model::index_uni(i))) -
                stan::model::rvalue(mu, "mu", stan::model::index_uni(i))) /
                stan::model::rvalue(sigma, "sigma", stan::model::index_uni(i))))),
              "assigning variable P", stan::model::index_uni(i));
          }
          current_statement__ = 44;
          for (int i = 1; i <= N_new; ++i) {
            current_statement__ = 43;
            stan::model::assign(R,
              (stan::math::Phi(
                 (((stan::model::rvalue(new_dates, "new_dates",
                      stan::model::index_uni(i)) -
                 stan::model::rvalue(tau, "tau",
                   stan::model::index_uni(((i + N_old) + N_moult)))) -
                 stan::model::rvalue(mu, "mu",
                   stan::model::index_uni(((i + N_old) + N_moult)))) /
                 stan::model::rvalue(sigma, "sigma",
                   stan::model::index_uni(((i + N_old) + N_moult))))) + (1 -
              stan::math::Phi(
                ((stan::model::rvalue(new_dates, "new_dates",
                    stan::model::index_uni(i)) -
                stan::model::rvalue(mu, "mu",
                  stan::model::index_uni(((i + N_old) + N_moult)))) /
                stan::model::rvalue(sigma, "sigma",
                  stan::model::index_uni(((i + N_old) + N_moult))))))),
              "assigning variable R", stan::model::index_uni(i));
          }
        }
        current_statement__ = 53;
        for (int i = 1; i <= N_moult; ++i) {
          current_statement__ = 52;
          stan::model::assign(q,
            (stan::math::log(
               stan::model::rvalue(tau, "tau",
                 stan::model::index_uni((i + N_old)))) +
            stan::math::normal_lpdf<false>(
              (stan::model::rvalue(moult_dates, "moult_dates",
                 stan::model::index_uni(i)) -
              (stan::model::rvalue(moult_indices, "moult_indices",
                 stan::model::index_uni(i)) *
              stan::model::rvalue(tau, "tau",
                stan::model::index_uni((i + N_old))))),
              stan::model::rvalue(mu, "mu",
                stan::model::index_uni((i + N_old))),
              stan::model::rvalue(sigma, "sigma",
                stan::model::index_uni((i + N_old))))),
            "assigning variable q", stan::model::index_uni(i));
        }
        current_statement__ = 54;
        stan::model::assign(log_lik,
          stan::math::append_row(
            stan::math::append_row(stan::math::log(P), q), stan::math::log(R)),
          "assigning variable log_lik");
      }
      out__.write(beta_mu_out);
      out__.write(beta_tau_out);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta_mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_pred_mu,
          DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta_mu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_pred_mu),
        "assigning variable beta_mu");
      out__.write(beta_mu);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_tau =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_pred_tau,
          DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta_tau,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_pred_tau),
        "assigning variable beta_tau");
      out__.write(beta_tau);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_pred_sigma,
          DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(beta_sigma,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_pred_sigma),
        "assigning variable beta_sigma");
      out__.write(beta_sigma);
      Eigen::Matrix<local_scalar_t__,-1,1> u_year_mean =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_years, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(u_year_mean,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_years),
        "assigning variable u_year_mean");
      out__.write(u_year_mean);
      Eigen::Matrix<local_scalar_t__,-1,1> u_year_duration =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_years, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(u_year_duration,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N_years),
        "assigning variable u_year_duration");
      out__.write(u_year_duration);
      local_scalar_t__ sd_year_mean = DUMMY_VAR__;
      current_statement__ = 6;
      sd_year_mean = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sd_year_mean);
      local_scalar_t__ sd_year_duration = DUMMY_VAR__;
      current_statement__ = 7;
      sd_year_duration = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sd_year_duration);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta_mu",
        "double", std::vector<size_t>{static_cast<size_t>(N_pred_mu)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_tau",
        "double", std::vector<size_t>{static_cast<size_t>(N_pred_tau)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "beta_sigma",
        "double", std::vector<size_t>{static_cast<size_t>(N_pred_sigma)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "u_year_mean",
        "double", std::vector<size_t>{static_cast<size_t>(N_years)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "u_year_duration",
        "double", std::vector<size_t>{static_cast<size_t>(N_years)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "sd_year_mean",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "sd_year_duration",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta_mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_pred_mu,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_mu_flat__;
        current_statement__ = 1;
        beta_mu_flat__ = context__.vals_r("beta_mu");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= N_pred_mu; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(beta_mu, beta_mu_flat__[(pos__ - 1)],
            "assigning variable beta_mu", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta_mu);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_tau =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_pred_tau,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_tau_flat__;
        current_statement__ = 2;
        beta_tau_flat__ = context__.vals_r("beta_tau");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= N_pred_tau; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(beta_tau, beta_tau_flat__[(pos__ - 1)],
            "assigning variable beta_tau", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta_tau);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_pred_sigma,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_sigma_flat__;
        current_statement__ = 3;
        beta_sigma_flat__ = context__.vals_r("beta_sigma");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= N_pred_sigma; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(beta_sigma, beta_sigma_flat__[(pos__ - 1)],
            "assigning variable beta_sigma", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta_sigma);
      Eigen::Matrix<local_scalar_t__,-1,1> u_year_mean =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_years, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> u_year_mean_flat__;
        current_statement__ = 4;
        u_year_mean_flat__ = context__.vals_r("u_year_mean");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(u_year_mean, u_year_mean_flat__[(pos__ - 1)],
            "assigning variable u_year_mean", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(u_year_mean);
      Eigen::Matrix<local_scalar_t__,-1,1> u_year_duration =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N_years, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> u_year_duration_flat__;
        current_statement__ = 5;
        u_year_duration_flat__ = context__.vals_r("u_year_duration");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(u_year_duration, u_year_duration_flat__[(pos__
            - 1)], "assigning variable u_year_duration",
            stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(u_year_duration);
      local_scalar_t__ sd_year_mean = DUMMY_VAR__;
      current_statement__ = 6;
      sd_year_mean = context__.vals_r("sd_year_mean")[(1 - 1)];
      out__.write_free_lb(0, sd_year_mean);
      local_scalar_t__ sd_year_duration = DUMMY_VAR__;
      current_statement__ = 7;
      sd_year_duration = context__.vals_r("sd_year_duration")[(1 - 1)];
      out__.write_free_lb(0, sd_year_duration);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta_mu", "beta_tau", "beta_sigma",
                "u_year_mean", "u_year_duration", "sd_year_mean",
                "sd_year_duration"};
    if (emit_transformed_parameters__) {
      std::vector<std::string>
        temp{"sigma_intercept", "beta_star", "tau_star", "u_year_mean_star",
             "u_year_duration_star"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"beta_mu_out", "beta_tau_out", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    N_pred_mu)},
                std::vector<size_t>{static_cast<size_t>(N_pred_tau)},
                std::vector<size_t>{static_cast<size_t>(N_pred_sigma)},
                std::vector<size_t>{static_cast<size_t>(N_years)},
                std::vector<size_t>{static_cast<size_t>(N_years)},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(N_years)},
             std::vector<size_t>{static_cast<size_t>(N_years)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N_pred_mu)},
             std::vector<size_t>{static_cast<size_t>(N_pred_tau)},
             std::vector<size_t>{static_cast<size_t>(log_lik_1dim__)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= N_pred_mu; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_pred_tau; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_tau" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_pred_sigma; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_sigma" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
      param_names__.emplace_back(std::string() + "u_year_mean" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
      param_names__.emplace_back(std::string() + "u_year_duration" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sd_year_mean");
    param_names__.emplace_back(std::string() + "sd_year_duration");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "sigma_intercept");
      param_names__.emplace_back(std::string() + "beta_star");
      param_names__.emplace_back(std::string() + "tau_star");
      for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
        param_names__.emplace_back(std::string() + "u_year_mean_star" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
        param_names__.emplace_back(std::string() + "u_year_duration_star" +
          '.' + std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N_pred_mu; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta_mu_out" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_pred_tau; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta_tau_out" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= log_lik_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= N_pred_mu; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_pred_tau; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_tau" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_pred_sigma; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_sigma" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
      param_names__.emplace_back(std::string() + "u_year_mean" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
      param_names__.emplace_back(std::string() + "u_year_duration" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sd_year_mean");
    param_names__.emplace_back(std::string() + "sd_year_duration");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "sigma_intercept");
      param_names__.emplace_back(std::string() + "beta_star");
      param_names__.emplace_back(std::string() + "tau_star");
      for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
        param_names__.emplace_back(std::string() + "u_year_mean_star" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_years; ++sym1__) {
        param_names__.emplace_back(std::string() + "u_year_duration_star" +
          '.' + std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N_pred_mu; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta_mu_out" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N_pred_tau; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta_tau_out" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= log_lik_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_mu) + "},\"block\":\"parameters\"},{\"name\":\"beta_tau\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_tau) + "},\"block\":\"parameters\"},{\"name\":\"beta_sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_sigma) + "},\"block\":\"parameters\"},{\"name\":\"u_year_mean\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_years) + "},\"block\":\"parameters\"},{\"name\":\"u_year_duration\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_years) + "},\"block\":\"parameters\"},{\"name\":\"sd_year_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sd_year_duration\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_intercept\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta_star\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"tau_star\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"u_year_mean_star\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_years) + "},\"block\":\"transformed_parameters\"},{\"name\":\"u_year_duration_star\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_years) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_mu_out\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_mu) + "},\"block\":\"generated_quantities\"},{\"name\":\"beta_tau_out\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_tau) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_lik_1dim__) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta_mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_mu) + "},\"block\":\"parameters\"},{\"name\":\"beta_tau\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_tau) + "},\"block\":\"parameters\"},{\"name\":\"beta_sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_sigma) + "},\"block\":\"parameters\"},{\"name\":\"u_year_mean\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_years) + "},\"block\":\"parameters\"},{\"name\":\"u_year_duration\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_years) + "},\"block\":\"parameters\"},{\"name\":\"sd_year_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sd_year_duration\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_intercept\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"beta_star\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"tau_star\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"u_year_mean_star\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_years) + "},\"block\":\"transformed_parameters\"},{\"name\":\"u_year_duration_star\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_years) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_mu_out\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_mu) + "},\"block\":\"generated_quantities\"},{\"name\":\"beta_tau_out\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N_pred_tau) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(log_lik_1dim__) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((N_pred_mu + N_pred_tau) + N_pred_sigma)
      + N_years) + N_years) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (((((1 + 1)
      + 1) + N_years) + N_years));
    const size_t num_gen_quantities = emit_generated_quantities *
      (((N_pred_mu + N_pred_tau) + log_lik_1dim__));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((N_pred_mu + N_pred_tau) + N_pred_sigma)
      + N_years) + N_years) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (((((1 + 1)
      + 1) + N_years) + N_years));
    const size_t num_gen_quantities = emit_generated_quantities *
      (((N_pred_mu + N_pred_tau) + log_lik_1dim__));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_uz2_linpred_annual_ranef_namespace::model_uz2_linpred_annual_ranef;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_uz2_linpred_annual_ranef_namespace::profiles__;
}
#endif
#endif
